// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvhujplinkybygcvixmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52aHVqcGxpbmt5YnlnY3ZpeG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTMxMDIsImV4cCI6MjA2OTM4OTEwMn0.M4EjjfVk9iDWDCfmwncfcjju-8Fckx3PQCAO51AuJMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});